### ISSUE TITLE
Non-standard EIP712 signature

### ISSUE THREAD

**Issue by georgeroman** [ZeframLou/trustus#3]
There is a bug in the EIP712 signature verification. Per https://eips.ethereum.org/EIPS/eip-712, dynamic types like `bytes` are encoded as the `keccak256` hash of their contents. In the below code, `packet.payload` should be replaced with `keccak256(packet.payload)`:
https://github.com/ZeframLou/trustus/blob/6f85ad390ad8d360fb1b9c72897a2dbd8f3e1a15/src/Trustus.sol#L109

**Comment by han1ue** [comment]
> There is a bug in the EIP712 signature verification. Per https://eips.ethereum.org/EIPS/eip-712, dynamic types like `bytes` are encoded as the `keccak256` hash of their contents. `packet.payload` should be replaced with `keccak256(packet.payload)`:
> 
> https://github.com/ZeframLou/trustus/blob/6f85ad390ad8d360fb1b9c72897a2dbd8f3e1a15/src/Trustus.sol#L109

Had the same problem exactly. Opening a pull request.

**Comment by ZeframLou** [comment]
Fixed by #4
